configuration:
  configuration_dir: "commons/config"
  template_dir:
  - "commons/templates"
  - "setupmobans/templates"
  - ".moban.d"
  configuration: pyexcel-io.yml
targets:
  - "docs/source/conf.py": "docs/source/conf.py"
  - setup.py: setup.py
  - .travis.yml: travis.yml.jj2
  - requirements.txt: requirements.txt.jj2
  - "tests/requirements.txt": "tests/requirements.txt"
  - LICENSE: NEW_BSD_LICENSE.jj2
  - MANIFEST.in: MANIFEST.in.jj2
  - test.sh: test.script.jj2
  - test.bat: test.script.jj2
  - README.rst: README.rst
  - "docs/source/index.rst": "docs/source/index.rst"
  - output: CHANGELOG.rst
    configuration: changelog.yml
    template: CHANGELOG.rst.jj2
